<?php

namespace MA\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert() {
        $qb = $this->createQuerybuilder('a'); // SELECT * FROM APPLICATIONS

        $qb->innerJoin('a.advert', 'adv')->addSelect('adv');

        $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
